<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0dd25pg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0dd25pg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0dd25pg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0dd25pg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0dd25pg\appDevDebugProjectContainer(array(
    'container.build_hash' => '0dd25pg',
    'container.build_id' => '4556a8e2',
    'container.build_time' => 1534410015,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0dd25pg');
